events/urls.py
from django.conf.urls import patterns, url
from events import views

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^create/$', views.create_event, name='create_event'),
    url(r'^(?P<event_id>\d+)/$', views.show_event, name='show_event'),
    url(r'^(?P<event_id>\d+)/edit/$', views.edit_event, name='edit_event'),
    url(r'^(?P<event_id>\d+)/attend/$', views.attend_event, name='attend'),
    url(r'^(?P<event_id>\d+)/attend/(?P<attendee_slug>[\d\w]{6})/$', views.show_attendee, name='show_attendee'),
    url(r'^(?P<event_id>\d+)/attend/(?P<attendee_slug>[\d\w]{6})/control/$', views.control_attendee, name='control_attendee'),
)

events/models.py
# -*- coding: utf-8  -*-
from django.db import models
from django.contrib.auth.models import User

class Event(models.Model):
    name = models.CharField(max_length=50, verbose_name=u"الاسم")
    submitter = models.ForeignKey(User, null=True,
                                  on_delete=models.SET_NULL,
                                  verbose_name=u"المرسل")
    location = models.CharField(max_length=50, verbose_name=u"المكان", blank=True, help_text=u"اسم القاعة مثلا.")
    location_description = models.TextField(verbose_name=u"تفاصيل المكان", help_text=u'الوصف مثلا', blank=True)
    long_position   = models.DecimalField (max_digits=10, decimal_places=5, verbose_name=u"خط الطول")
    lat_position   = models.DecimalField (max_digits=10, decimal_places=5, verbose_name=u"خط العرض")
    short_description = models.TextField(u'الوصف القصير', help_text=u"سيستخدم في الصفحة الرئيسية للأنشطة (يمكن استخدام HTML")
    description = models.TextField(u'الوصف', help_text=u"الوصف الكامل (يمكن استخدام HTML)")
    starting_date = models.DateTimeField(u'تاريخ ووقت بدء الحدث')
    ending_date =  models.DateTimeField(u'تاريخ ووقت انتهاء')
    announcement_date =  models.DateField(u'تاريخ الإعلان', help_text=u"متى تريد أن يظهر هذا النشاط للزوار؟")
    max_attendees = models.PositiveSmallIntegerField(verbose_name=u"العدد الأقصى للحضور", help_text=u"كم عدد التذاكر التي سيسمح بحجزها؟")
    submission_date = models.DateTimeField(u'تاريخ الإرسال',
                                           auto_now_add=True)
    available_to_choices = (
        ('A', u'الجميع'),
        ('F', u'النساء'),
        ('M', u'الرجال'),
        )
    available_to = models.CharField(max_length=1,
                                    verbose_name=u"متاح لـ",
                                    choices=available_to_choices)
    edit_date = models.DateTimeField(u'تاريخ التعديل', auto_now=True)

    def __unicode__(self):
        return self.name
    
class Attendee(models.Model):
    event = models.ForeignKey(Event, null=True,
                              on_delete=models.SET_NULL,
                              verbose_name=u"الحدث")
    name = models.CharField(max_length=100, verbose_name=u"الاسم")
    email = models.EmailField(u'البريد')
    gender_choices = (
        ('M', u'ذكر'),
        ('F', u'أنثى'),
        )
    gender = models.CharField(max_length=1, verbose_name=u"الجنس", choices=gender_choices)
    add_to_mailing_list = models.BooleanField(verbose_name=u"هل تريد أن تضاف إلى القائمة البريدية؟",
                                              default=True)
    referral_choices = (
        ('T', u'قرأت عنه في تويتر'), # Twitter
        ('F', u'قرأت عنه في فيسبوك'),  # Facebook
        ('P', u'شاهدت إعلانا معلقا'), # Poster
        ('M', u'أخبرني عنه صديق'), # Word-of-mouth
        ('W', u'موقع المجموعة'), # Our website
        )
    referral = models.CharField(max_length=1, verbose_name=u"كيف عرفت عن الحدث؟", choices=referral_choices)
    slug = models.CharField(max_length=6, verbose_name=u"رابط")
    submission_date = models.DateTimeField(u'تاريخ الإرسال',
                                           auto_now_add=True)
    edit_date = models.DateTimeField(u'تاريخ التعديل', auto_now=True)
    is_counted_choices = (
        (False, 'ملغى'),
        (True, 'محسوب'),
        )
    is_counted = models.BooleanField(verbose_name=u"محسوب",
                                     default=True,
                                     choices=is_counted_choices)

    def __unicode__(self):
        return u"%s: %s" % (self.event.name, self.slug)

class Organizer(models.Model):
    event = models.ForeignKey(Event, null=True,
                              on_delete=models.SET_NULL,
                              verbose_name=u"الحدث")
    name = models.CharField(max_length=100, verbose_name=u"الاسم")
    email = models.EmailField(u'البريد')
    gender_choices = (
        ('M', u'ذكر'),
        ('F', u'أنثى'),
        )
    gender = models.CharField(max_length=1, choices=gender_choices,
                              verbose_name=u"الجنس")
    add_to_mailing_list = models.BooleanField(verbose_name=u"هل تريد أن تضاف إلى القائمة البريدية؟",
                                              default=True)
    submission_date = models.DateTimeField(u'تاريخ الإرسال',
                                           auto_now_add=True)
    edit_date = models.DateTimeField(u'تاريخ التعديل', auto_now=True)
    status_choices = (
        (None, 'لم يراجع بعد'),
        (False, 'مرفوض'),
        (True, 'مقبول'),
        )
    status = models.NullBooleanField(verbose_name=u"الحالة",
                                     default=None,
                                     choices=status_choices)

events/templates/events/attend_event.html
{% extends 'events/event_base.html' %}{% load bootstrap3 %}
{% block title %}حضور {{ event.name }}{% endblock %}
{% block content %}
<h2>حضور <a href="{% url 'events:show_event' event.pk %}">{{ event.name }}</a></h2>
{% if error %}
	<p class="alert alert-warning">
	{% if error == 'booked' %}
	حجزت جميع المقاعد، ولم يعد ممكنا التسجيل في هذا النشاط. نتطلع لرؤيتك في نشاط قادم!
	{% elif error == 'done' %}
		{% if edit %}
	انتهى {{ event.name }} ولم يعد بمقدورك تعديل معلومات حضورك.
		{% else %}
	انتهى {{ event.name }} ولم يعد بمقدورك التسجيل.
		{% endif %}
	{% elif error == 'unavailable' %}
	هذا النشاط غير متاح للتسجيل بعد.
	{% endif %}
</p>
{% else %}
{% if event.available_to != 'A' %}
	<p class="alert alert-warning">
	{% if event.available_to == 'M' %}نود أن ننوه إلى أن هذا النشاط متاح للرجال فقط.{% endif %}
	{% if event.available_to == 'F' %}نود أن ننوه إلى أن هذا النشاط متاح للنساء فقط.{% endif %}
	</p>
{% endif %}

	<form action="{% if edit %}{% url 'events:control_attendee' event.pk attendee.slug %}{% else %}{% url 'events:attend' event.pk %}{% endif %}" method="post" class="form">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<button type="submit" class="btn btn-success">
				{% if edit %}{% bootstrap_icon "pencil" %} عدّل {% else %} {% bootstrap_icon "ok-sign" %} سجّل {% endif %}
			</button>
		{% endbuttons %}
	</form>
	{% if edit %}
	<form action="{% url 'events:control_attendee' event.pk attendee.slug %}" method="post" class="form">
		{% csrf_token %}
		<input type="hidden" name="action" value="cancel"/>
		{% buttons %}
			<button type="submit" class="btn btn-danger">
				{% bootstrap_icon "remove" %} ألغِ
			</button>
		{% endbuttons %}
	</form>
	{% endif %}
{% endif %}
{% endblock %}

events/templates/events/create_event.html
{% extends 'events/event_base.html' %}{% load bootstrap3 %}
{% block title %}{% if edit %} تعديل {{ event.name }}{% else %}إضافة نشاط{% endif %}{% endblock %}
{% block content %}
<h2>{% if edit %} تعديل {{ event.name }}{% else %}إضافة نشاط{% endif %}</h2>
	<form action="{% if edit %}{% url 'events:edit_event' event.pk %}{% else %}{% url 'events:create_event' %}{% endif %}" method="post" class="form">
		{% csrf_token %}
		{% bootstrap_form form %}
			{% buttons %}
			<button type="submit" class="btn btn-primary">
				{% if edit %}{% bootstrap_icon "pencil" %} عدّل {% else %} {% bootstrap_icon "ok-sign" %} أضف {% endif %}
		        </button>
			{% endbuttons %}
	</form>
<script>
$(function(){
	$('#id_announcement_date').datepicker({isRTL: true});
});
</script>
{% endblock %}

events/templates/events/event_base.html
{% extends 'base.html' %}{% load bootstrap3 %}
{% block events %} class="active"{% endblock %}
{% block title %}{% endblock %}
{% block content %}{% endblock %}

events/templates/events/home.html
{% extends 'events/event_base.html' %}{% load staticfiles %}
{% block title %}قائمة نشطات المجموعة{% endblock %}
{% block content %}


{% if next_event %}
<div class="row" id="next-event">
      <div class="col-md-6 col-sm-12 text-center">
	<h2>{{ next_event.name }}</h2>
	
	<p>&nbsp;</p>
	<p class="text-center">{{ next_event.short_description|safe }}</p>
	
	<div class="actions">
	  <a class="btn btn-default btn-lg" href="{% url 'events:show_event' next_event.pk %}">
	    انضم إلينا
	  </a>
	</div>
	
      </div>
      <div class="col-md-6 col-sm-12">
      <div class="row text-center">
      <img src="{% if next_event.image %}{{ next_event.image }}{% else %}{% static 'img/user.png' %}{% endif %}" class="img-rounded">
      </div>
    </div>
</div>
{% endif %}
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">نشاطات المجموعة {% if perms.events.add_event %}<a href="{% url 'events:create_event' %}">(أنشئ)</a>{% endif %}</h3>
	</div>
	 <div class="panel-body">
		{% if page_events %}

		<table class="table table-hover">
			<thead>
				<tr>
					<th>الحدث</th>
					<th>الوقت</th>
					<th>المكان</th>
					<th></th>
				</tr>
			</thead>
			 <tbody>
				{% for e in page_events %}
				<tr>
					<td><a href="{% url 'events:show_event' e.pk %}">{{ e.name }}</a></td>
                       			<td>{{ e.starting_date|date:"j F Y" }}</td>
                       			<td>{{ e.location }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		<div style="text-align:center;">
		    <span class="step-links">
		        {% if page_events.has_previous %}
		            <a href="?page={{ page_events.previous_page_number }}">السابق</a>
		        {% endif %}

        		<span class="current">
		            الصفحة {{ page_events.number }} من {{ page_events.paginator.num_pages }}
		        </span>

        		{% if page_events.has_next %}
		            <a href="?page={{ page_events.next_page_number }}">التالي</a>
		        {% endif %}
		    </span>
		</div>
		{% else %}
			<p>لا توجد نشاطات.</p>
		{% endif %}
	</div>
</div>

{% endblock %}

events/templates/events/show_attendee.html
{% extends 'events/event_base.html' %}
{% block title %}{{ attendee.event.name }}{% endblock %}
{% block content %}
<h2>تذكرة حضور <a href="{% url 'events:show_event' attendee.event.pk %}">{{ attendee.event.name }}</a> {% if not attendee.is_counted %}<span style="color: red;">(ملغاه)</span>{% endif %}</h2>

<div class="row">
	<div class="col-md-9">
	<table class="table-hover table">
		<colgroup>
			<col class="col-xs-2">
			<col class="col-xs-7">
		</colgroup>
		<tr>
			<th>الاسم</th>
			<td>{{ attendee.name }}</td>
		</tr>
		<tr>
			<th>الجنس</th>
			<td>{{ attendee.get_gender_display }}</td>
		</tr>
		<tr>
			<th>كيف تعرفت على النشاط؟</th>
			<td>{{ attendee.get_referral_display }}</td>
		</tr>
	</table>
	</div>

	<div class="col-md-3">
		{% if editable and attendee.is_counted %}
			<p><a href="{% url 'events:control_attendee' attendee.event.pk attendee.slug %}" class="form-control btn btn-warning"><span class="glyphicon glyphicon-pencil"></span> عدّل أو ألغِ</a></p>
		{% endif %}
	</div>

</div>

{% endblock %}

events/templates/events/show_event.html
{% extends 'events/event_base.html' %}{% load staticfiles %}
{% block title %}{{ event.name }}{% endblock %}
{% block meta %}
    <meta property="twitter:card" content="summary" />
    <meta property="twitter:site" content="@RLUGroup" />
    <meta property="twitter:creator" content="@RLUGroup" />
    <meta property="twitter:title" content="{{ event.name }}" />
    <meta property="twitter:description" content="{{ event.short_description|striptags }}" />
    <meta property="twitter:url" content="{{ full_url }}" />
{% endblock %}
{% block content %}
<div class="row">
<h2 id="event-name">{{ event.name }}{% if perms.events.change_event %} (<a href="{% url 'events:edit_event' event.pk %}">عدّل</a>){% endif %}</h2>
</div>
<div class="row">
	<div class="col-md-9">
		<div id="eventmap"></div> 
	</div>
	<div class="col-md-3">

<div id="attend-panel" class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">احضر!</h3>
	</div>
	 <div class="panel-body">
			<p>
		{% if attendable == 'yes' %}
			ككل نشاطات المجموعة هذا النشاط مجاني عمومي. <strong>{{ event.name }}</strong> متاح
			{% if event.available_to == 'M' %}للرجال
			{% elif event.available_to == 'F' %}للنساء
			{% elif event.available_to == 'A' %}للجميع رجالا ونساءً
			{% endif %} لكن ينبغي تسجيل الحضور. <a id="attend-link" href="{% url 'events:attend' event.pk %}">سجّل حضورك الآن</a>

		{% elif attendable == 'over' %}
			انتهى الحدث. نراك في <a href="{% url 'events:home' %}">حدث قادم</a>!
		{% elif attendable == 'booked' %}
			اكتمل حجز مقاعد هذا الحدث ولم يعد ممكنا التسجيل لحضوره. نراك في <a href="{% url 'events:home' %}">حدث قادم</a>!
		{% endif %}
			</p>
	</div>
</div>
	</div>
</div>
<div class="row">
	<div class="col-md-9">
	<table class="table-hover table">
		<colgroup>
			<col class="col-xs-2">
			<col class="col-xs-7">
		</colgroup>
		<tr>
			<th>الوصف</th>
			<td>{{ event.description|safe }}</td>
		</tr>
		<tr>
			<th>المكان</th>
			<td>{{ event.location }}<br/>{{ event.location_description }}<br/>الإحداثيات: {{ event.lat_position|stringformat:"f" }}, {{ event.long_position|stringformat:"f" }}</td>
		</tr>
	</table>
	</div>
	<div class="col-md-3">
		<div id="time" class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">متى؟</h3>
			</div>
			 <div class="panel-body">
				{% if event.starting_date|date:"nj" == event.ending_date|date:"nj" %}
					<p>{{ event.starting_date|date:"l j F o"  }}<br/>من {{ event.starting_date|date:"g:iA"  }} إلى {{ event.ending_date|date:"g:iA"  }}</p>
				{% else %}
					<p><strong>البدء:</strong> {{ event.starting_date }}<br/><strong>الانتهاء:</strong> {{ event.ending_date }}</p>
				{% endif %}
			</div>
		</div>
	</div>
</div>
<script src="{% static 'js/openlayers/OpenLayers.js'%}"></script>
<script>
$(function() {
        map = new OpenLayers.Map("eventmap");
        var mapnik         = new OpenLayers.Layer.OSM();
        var fromProjection = new OpenLayers.Projection("EPSG:4326");   // Transform from WGS 1984
        var toProjection   = new OpenLayers.Projection("EPSG:900913"); // to Spherical Mercator Projection
        var position       = new OpenLayers.LonLat({{ event.long_position|stringformat:"f" }}, {{ event.lat_position|stringformat:"f" }}).transform( fromProjection, toProjection);
        var zoom           = 15;
        var markers = new OpenLayers.Layer.Markers( "Markers" );
        map.addLayer(markers);
        map.addLayer(mapnik);
        markers.addMarker(new OpenLayers.Marker(position));
        map.setCenter(position, zoom );
      });
</script>
{% endblock %}